export type TScreeningResult = {
  sektor: string;
  subsektor: string;
  general: {
    ticker: string;
    tahun: number;
    periode: number;
    currency: "IDR" | "USD";
    multiply: number;
  };
  income: {
    "Penjualan dan pendapatan usaha": number;
    "Pendapatan (beban) pajak": number;
    "Jumlah laba (rugi)": number;
  };
  cashflow: {
    OperatingCash: number;
    InvestingCash: number;
    FinancingCash: number;
    "Jumlah kenaikan (penurunan) bersih kas dan setara kas": number;
    "Kas dan setara kas arus kas, awal periode": number;
    "Kas dan setara kas arus kas, akhir periode": number;
  };
  balance: BankBalance | GeneralBalance;
  dividen: number | string;
};

type BankBalance = {
  Kas: 12041582;
  "Giro pada bank indonesia asset": number;
  "Giro pada bank lain asset": number;
  "Giro pada bank lain pihak ketiga asset": number;
  "Giro pada bank lain pihak berelasi asset": number;
  "Cadangan kerugian penurunan nilai pada giro pada bank lain": number;
  "Cadangan kerugian penurunan nilai pada penempatan pada bank lain": number;
  "Cadangan kerugian penurunan nilai pada piutang asuransi": number;
  "Deposito pada lembaga kliring dan penjaminan": number;
  "Cadangan kerugian penurunan nilai pada efek-efek yang diperdagangkan": number;
  "Cadangan kerugian penurunan nilai pada wesel ekspor dan tagihan lainnya": number;
  "Cadangan kerugian penurunan nilai pada tagihan akseptasi": number;
  "Cadangan kerugian penurunan nilai pada pinjaman yang diberikan": number;
  "Cadangan kerugian penurunan nilai pada piutang nasabah": number;
  "Cadangan kerugian penurunan nilai pada piutang murabahah": number;
  "Cadangan kerugian penurunan nilai pada piutang istishna": number;
  "Cadangan kerugian penurunan nilai pada piutang ijarah": number;
  "Cadangan kerugian penurunan nilai pada piutang pembiayaan konsumen": number;
  "Cadangan kerugian penurunan nilai pada pinjaman qardh": number;
  "Cadangan kerugian penurunan nilai pada pembiayaan mudharabah": number;
  "Cadangan kerugian penurunan nilai pada pembiayaan musyarakah": number;
  "Cadangan kerugian penurunan nilai pada investasi sewa": number;
  "Cadangan kerugian penurunan nilai pada tagihan anjak piutang": number;
  "Cadangan kerugian penurunan nilai pada piutang lainnya": number;
  "Total biaya dimuka": number;
  "Jumlah aset tidak lancar": number;
  "Jumlah aset lancar": number;
  "Giro liabilitas": number;
  "Giro pihak ketiga liabilitas": number;
  "Giro pihak berelasi liabilitas": number;
  "Giro wadiah liabilitas": number;
  "Giro wadiah pihak ketiga liabilitas": number;
  "Giro wadiah pihak berelasi liabilitas": number;
  Tabungan: number;
  "Tabungan pihak ketiga": number;
  "Tabungan pihak berelasi": number;
  "Tabungan wadiah": number;
  "Tabungan wadiah pihak ketiga": number;
  "Tabungan wadiah pihak berelasi": number;
  "Deposito berjangka": number;
  "Deposito berjangka pihak ketiga": number;
  "Deposito berjangka pihak berelasi": number;
  "Deposito wakalah": number;
  "Deposito wakalah pihak ketiga": number;
  "Deposito wakalah pihak berelasi": number;
  "Jumlah liabilitas jangka pendek": number;
  "Jumlah liabilitas jangka panjang": number;
  "Giro mudharabah liabilitas": number;
  "Giro mudharabah pihak ketiga liabilitas": number;
  "Giro berjangka mudharabah pihak berelasi liabilitas": number;
  "Tabungan mudharabah": number;
  "Tabungan mudharabah pihak ketiga": number;
  "Tabungan mudharabah pihak berelasi": number;
  "Deposito berjangka mudharabah": number;
  "Deposito berjangka mudharabah pihak ketiga": number;
  "Deposito berjangka mudharabah pihak berelasi": number;
  "Tabungan mudharabah (ummat)": number;
  "Jumlah ekuitas": number;
  "Total jumlah persediaan": number;
};

type GeneralBalance = {
  "Persediaan lancar": number;
  "Persediaan hewan ternak lancar": number;
  "Persediaan aset real estat lancar": number;
  "Persediaan lancar lainnya": number;
  "Biaya dibayar dimuka lancar": number;
  "Pajak dibayar dimuka lancar": number;
  "Jumlah aset lancar": number;
  "Biaya dibayar dimuka tidak lancar": number;
  "Pajak dibayar dimuka tidak lancar": number;
  "Persediaan tidak lancar": number;
  "Persediaan hewan ternak tidak lancar": number;
  "Persediaan tidak lancar lainnya": number;
  "Jumlah aset tidak lancar": number;
  "Jumlah aset": number;
  "Pendapatan diterima dimuka jangka pendek": number;
  "Jumlah liabilitas jangka pendek": number;
  "Pendapatan diterima dimuka jangka panjang": number;
  "Jumlah liabilitas jangka panjang": number;
  "Jumlah liabilitas": number;
  "Jumlah ekuitas": number;
  "Total jumlah persediaan": number;
  "Total biaya dimuka": number;
};
